### ISSUE TITLE
你好，不换字体的情况下适用吗？有需要微调的地方吗

### ISSUE THREAD

**Issue by jorismq** [arashaan/MacType-Profile#1]
大部分字体我会用“微软雅黑”

谢谢

**Comment by arashaan** [comment]
Yeah. it doesn't matter which we used. it depends on what we expect from a font
For me, macOS builtin font is pretty interesting. ofcourse it has so many missing glyphs for windows ttf font support, but finally i still love it

是的 不管使用哪个。 这取决于我们对字体的期望
对我来说，macOS内置字体非常有趣。 当然，它对于Windows ttf字体支持有很多缺失的字形，但最后我还是喜欢它
(TRANSLATED by GOOGLE TRANSLATE)
